name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: "!contains(github.event.commits[0].message, '[skip-ci]')"
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and Restart Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.DESTINATION }}
            git pull origin main
            RUSTFLAGS="-C target-cpu=native" /usr/bin/cargo build --release
            pm2 restart 1
