name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: "!contains(github.event.commits[0].message, '[skip-ci]')"
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup SSH Key
      - run: |
          echo '${{secrets.DEPLOYKEY}}' > deploy_key
          chmod 600 ./deploy_key

      - name: Build and Restart Application
        run: sh -i ./deploy_key -o 'StrictHostKeyChecking no' -v ${{env.REMOTE}} 'cd ${{secrets.DESTINATION}};git pull origin main;RUSTFLAGS="-C target-cpu=native" cargo build --release;pm2 restart 1'
